// Generated by build/write_buildflag_header.py
// From base_win_features


#ifndef BASE_DEBUG_DEBUGGING_FLAGS_
#define BASE_DEBUG_DEBUGGING_FLAGS_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_PROFILING() 1
#define BUILDFLAG_INTERNAL_ENABLE_SYSLOG() 0

#endif // BASE_DEBUG_DEBUGGING_FLAGS_