// Generated by build/write_buildflag_header.py
// From base_win_features


#ifndef BASE_ALLOCATOR_FEATURES_
#define BASE_ALLOCATOR_FEATURES_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_USE_EXPERIMENTAL_ALLOCATOR_SHIM() 0
#define BUILDFLAG_INTERNAL_ENABLE_WIN_ALLOCATOR_SHIM_TESTS() 1

#endif // BASE_ALLOCATOR_FEATURES_