// Generated by build/write_buildflag_header.py
// From base_win_features


#ifndef BASE_WIN_BASEFEATURES_
#define BASE_WIN_BASEFEATURES_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_SINGLE_MODULE_MODE_HANDLE_VERIFIER() 1

#endif // BASE_WIN_BASEFEATURES_